### ISSUE TITLE
Unet model

### ISSUE THREAD

**Issue by Laveena-S** [showlab/Tune-A-Video#11]
No pretrained unet model provided

**Comment by dawei03896** [comment]
+1

**Comment by zhangjiewu** [comment]
The pretrained unet model is under the folder of [stable-diffusion-v1-4](https://huggingface.co/CompVis/stable-diffusion-v1-4).

**Comment by dawei03896** [comment]
Thank you for your reply. I have a question. Does every input source video and source_prompt need to be retrained?

**Comment by zhangjiewu** [comment]
Yes.

**Comment by zhangjiewu** [comment]
Closed as solved. Feel free to reopen it if you have any other question.
