### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by zcdliuwei** [showlab/Tune-A-Video#14]
RuntimeError: CUDA out of memory. Tried to allocate 4.00 GiB (GPU 0; 23.70 GiB total capacity; 8.31 GiB already allocated; 254.06 MiB free; 8.76 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

My server environment is：
![image](https://user-images.githubusercontent.com/36565076/217143994-c9d4e174-6134-4106-9068-92857e3981bf.png)

**Comment by zhangjiewu** [comment]
Is [xformers](https://github.com/facebookresearch/xformers) installed and enabled?

**Comment by zhangjiewu** [comment]
You need to install xformers to avoid OOM. For installation, please follow the [official instruction](https://github.com/facebookresearch/xformers#installing-xformers).

**Comment by zcdliuwei** [comment]
I executed pip install xformers==0.16rc425 to install xformers, and torch==1.13.1, torch vision==0.14.1, and then encountered the following error during training:

![image](https://user-images.githubusercontent.com/36565076/217479484-bea0449c-312e-421c-96fe-5570400ae6ae.png)

**Comment by zhangjiewu** [comment]
It looks like you're using distributed training, which is not supported now. To avoid using multiple GPUs, you may specify one GPU device by `export CUDA_VISIBLE_DEVICES=GPU_ID`.

**Comment by zcdliuwei** [comment]
> 
I specified a visible device like below
CUDA_VISIBLE_DEVICES=0 accelerate launch train_tuneavideo.py --config="configs/man-surfing.yaml" 
but I still encountered the same error

**Comment by zhangjiewu** [comment]
can you try using the same environment as written in the `requirements.txt`? in particular, `torch==1.12.1`.

**Comment by zcdliuwei** [comment]
I have reinstalled the environment and can run normally, but the effect is not as good as that in your readmen file. Can you give me any suggestions for improvement

The following is the GIF I generated

![a panda is surfing](https://user-images.githubusercontent.com/36565076/217778605-4cb4a4d9-2036-4abb-8c6a-5b6b64fd23b5.gif)

![sks mr potato head is surfing in the forest](https://user-images.githubusercontent.com/36565076/217778635-5b5af4f3-5b7e-4691-8b80-c4c94d7b5ad6.gif)

**Comment by zhangjiewu** [comment]
https://github.com/showlab/Tune-A-Video/issues/15#issuecomment-1422110060 this might help

**Comment by StevensXu** [comment]
> It looks like you're using distributed training, which is not supported now. To avoid using multiple GPUs, you may specify one GPU device by `export CUDA_VISIBLE_DEVICES=GPU_ID`.

Why doesn't it support multi-gpu training, will it be difficult to modify the code to multi-gpu training?

**Comment by mayuelala** [comment]
> > It looks like you're using distributed training, which is not supported now. To avoid using multiple GPUs, you may specify one GPU device by `export CUDA_VISIBLE_DEVICES=GPU_ID`.
> 
> Why doesn't it support multi-gpu training, will it be difficult to modify the code to multi-gpu training?

I tried multi-gpu training, but results are bad
