### ISSUE TITLE
Change the device 0 to 1

### ISSUE THREAD

**Issue by uzumakinaruto19** [showlab/Tune-A-Video#16]
How do I change the device 0 to one so that Pytorch will use device cuda 1

@zhangjiewu ?

**Comment by archana0297** [comment]
![image](https://user-images.githubusercontent.com/43675432/217206412-1aeac803-7f93-42ed-bba1-05c5e3549545.png)

**Comment by zhangjiewu** [comment]
> How do I change the device 0 to one so that Pytorch will use device cuda 1
> 
> @zhangjiewu ?

@uzumakinaruto19 You may use `export CUDA_VISIBLE_DEVICES=GPU_ID` to specify a GPU device.

**Comment by zhangjiewu** [comment]
@archana0297 It seems you've installed an incompatible pytorch version. You may reinstall pytorch following the [official guideline](https://pytorch.org/get-started/locally/).
