### ISSUE TITLE
Pretraining model download

### ISSUE THREAD

**Issue by JWFanggit** [showlab/Tune-A-Video#19]
I can only download ckpt weight files， raise EnvironmentError(f"It looks like the config file at '{config_file}' is not a valid JSON file.")
OSError: It looks like the config file at './checkpoints/stable-diffusion-v1-4/sd-v1-4.ckpt' is not a valid JSON file.

**Comment by PotatoLzy** [comment]
Hi, there. I suffered the same question, can you tell me how you fixed that problem?
