### ISSUE TITLE
CUDA error: invalid argument

### ISSUE THREAD

**Issue by Fitz135** [showlab/Tune-A-Video#21]
I have met some problems when I run the code. I think maybe there is something wrong with "accelerator.backward(loss)" in line 294 in train_tuneavideo.py. Hope to seek your valuable opinions. Thank you.
![image](https://user-images.githubusercontent.com/45041887/218463503-d5d09723-2b93-4e80-a668-6ba499871400.png)

**Comment by zhangjiewu** [comment]
looks like it is caused by xformers. can you try disabling `enable_xformers_memory_efficient_attention` in config file?

**Comment by Fitz135** [comment]
I installed another version of xfomers. The problem has been solved. Thanks.
