### ISSUE TITLE
Question about the results

### ISSUE THREAD

**Issue by liangbingzhao** [showlab/Tune-A-Video#22]
I followed your README, modifying nothing of your code. Here is the final results, not that promising. What's more, I find that sample-100, sample-200 and sample-300 did not change much.  Can u share how to improve it?

![sample-300](https://user-images.githubusercontent.com/55656865/218621790-1c850620-22a1-48d1-ae50-0e231f4db0d1.gif)

**Comment by zhangjiewu** [comment]
please refer to https://github.com/showlab/Tune-A-Video/issues/15

**Comment by liangbingzhao** [comment]
Thank you, it seems like the xformers installation problem
