### ISSUE TITLE
Totally bad results, cannot reproduce!

### ISSUE THREAD

**Issue by LANYAN1212** [showlab/Tune-A-Video#28]
Why I cannot reproduce your results, and actually the results are quite bad...
The only different thing is that I have not installed the xformer package, and I reduce the n_sample_frames=12.
![WX{OMP3B7P7LVQ}AB_TZ(TJ](https://user-images.githubusercontent.com/56435130/222452944-70734be1-1762-4426-b600-a5c1c4ddb683.png)

**Comment by LANYAN1212** [comment]
![(K~X5WPPZ2$MVPQ(@TC6RRN](https://user-images.githubusercontent.com/56435130/222453043-5ccc378c-4fb0-4e9d-9413-687638fc8cb5.png)

**Comment by G-U-N** [comment]
My reproduced result is much better than yours.

**Comment by G-U-N** [comment]
![Iron Man is skiing on the snow](https://user-images.githubusercontent.com/60997859/223410719-dc93ab06-92c2-4db7-9b69-40188fec8e3b.gif)

**Comment by Randle-Github** [comment]
> I had similar problems when running with StableDiffusion V2. Switching to V1-4 worked for me.

I had the similar results as yours. Did you find the reasons?
