### ISSUE TITLE
Have you received a letter from your lawyer? If not, I will introduce a photo of a certain celebrity in my future research. Because I am a true ikun.

### ISSUE THREAD

**Issue by 1012537710** [showlab/Tune-A-Video#37]
Have you received a letter from your lawyer? If not, I will introduce a photo of a certain celebrity in my future research. Because I am a true ikun.

**Comment by wgp666** [comment]
666

**Comment by wgp666** [comment]
只因你太美

**Comment by RealHurrison** [comment]
Chicken You Are So Beautiful

**Comment by EricLee0224** [comment]
Intersting issue! If this teaser diagram is legal and does not have any legal conflicts of interest, please let me know! We are happy to contribute this hottest internal entertainment IP to the academic community!

**Comment by zhyzhyzhy123** [comment]
第一眼看成layer，还在想为啥laye还能发消息
