### ISSUE TITLE
Diffuser issue

### ISSUE THREAD

**Issue by 111111m** [showlab/Tune-A-Video#40]
I have installed the dev version diffuser from hugging face and gets this error "ModuleNotFoundError: No module named 'diffusers.modeling_utils'"

How shold I solve it?

**Comment by zhangjiewu** [comment]
`pip install diffusers[torch]==0.11.1`

**Comment by cjfcsjt** [comment]
for new versions of diffusers, change to `diffusers.models.modeling_utils`

**Comment by hunzai** [comment]
`diffusers== 0.21.4`
use
`from diffusers  import ModelMixin`

**Comment by gexmbla** [comment]
these short answers make a newbie's head ache. care to elaborate?

**Comment by LukeLIN-web** [comment]
> these short answers make a newbie's head ache. care to elaborate?

for new versions of diffusers, change to `from diffusers.models.modeling_utils import ModelMixin  `

**Comment by saberzaid** [comment]
what the fix

**Comment by MREDZ7** [comment]
I'm getting this error also. Can someone please explain in simple terms, step by step, how to fix the problem. Thanks :)

**Comment by HelloThere-yougothacked** [comment]
@MREDZ7 just go into the stable diffusion web ui folder, open in terminal and run pip install diffusers[torch]==0.11.1
