### ISSUE TITLE
ValueError : xformers is not available. Make sure it is installed correctly

### ISSUE THREAD

**Issue by yinxi26** [showlab/Tune-A-Video#43]
When I run "trian_tuneavideo_py"  I got this ValueError,  how can I deal this or how to install it?

**Comment by zhangjiewu** [comment]
please install xformers following [this](https://github.com/facebookresearch/xformers#installing-xformers) instruction.

**Comment by yinxi26** [comment]
Thanks for your help

**Comment by luccachiang** [comment]
@zhangjiewu Hello, what is your xformers version. I tried several times and failed. The official instruction recommend an installation with `torch==2.1.2`, but our requirements specify torch to be `1.12.1`. Btw, what is your cuda version? My cuda version is `11.1`. Maybe it is too old...

**Comment by shani1610** [comment]
@luccachiang i have the same conflict but with cuda 12, were you able to solve it?

**Comment by baolongwj** [comment]
> @zhangjiewu Hello, what is your xformers version. I tried several times and failed. The official instruction recommend an installation with `torch==2.1.2`, but our requirements specify torch to be `1.12.1`. Btw, what is your cuda version? My cuda version is `11.1`. Maybe it is too old...

hello,you can run
`pip install -v xformers==0.0.16` torch1.13 can run the code too
