### ISSUE TITLE
当下载完成所需的预先条件后，遇到运行出错的问题，不知该如何设置参数

### ISSUE THREAD

**Issue by SherZXH** [showlab/Tune-A-Video#44]
![屏幕截图_20230330_150548](https://user-images.githubusercontent.com/33541883/228756333-98958367-35c6-4a8a-909e-27e456ecb9e3.png)
请问如何解决呢

**Comment by volnet** [comment]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchtext 0.14.1 requires torch==1.13.1, but you have torch 1.12.1 which is incompatible.
torchaudio 0.13.1+cu116 requires torch==1.13.1, but you have torch 1.12.1 which is incompatible.
Successfully installed accelerate-0.18.0 antlr4-python3-runtime-4.9.3 bitsandbytes-0.35.4 decord-0.6.0 diffusers-0.11.1 einops-0.6.0 ftfy-6.1.1 huggingface-hub-0.13.3 modelcards-0.1.6 omegaconf-2.3.0 tokenizers-0.13.2 torch-1.12.1 torchvision-0.13.1 transformers-4.27.4

**Comment by zhangjiewu** [comment]
> ![屏幕截图_20230330_150548](https://user-images.githubusercontent.com/33541883/228756333-98958367-35c6-4a8a-909e-27e456ecb9e3.png) 请问如何解决呢

看起来是GPU的问题，建议检查一下GPU是否正常。

**Comment by zhangjiewu** [comment]
> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts. torchtext 0.14.1 requires torch==1.13.1, but you have torch 1.12.1 which is incompatible. torchaudio 0.13.1+cu116 requires torch==1.13.1, but you have torch 1.12.1 which is incompatible. Successfully installed accelerate-0.18.0 antlr4-python3-runtime-4.9.3 bitsandbytes-0.35.4 decord-0.6.0 diffusers-0.11.1 einops-0.6.0 ftfy-6.1.1 huggingface-hub-0.13.3 modelcards-0.1.6 omegaconf-2.3.0 tokenizers-0.13.2 torch-1.12.1 torchvision-0.13.1 transformers-4.27.4

you can reinstall the `torchtext` and `torchaudio` to the version that is compatible with `torch==1.12.1`, or directly uninstall these two packages as they are not used in our code.
