### ISSUE TITLE
How Can It Tuned in M1 clip?

### ISSUE THREAD

**Issue by Moretai** [showlab/Tune-A-Video#45]
<img width="964" alt="image" src="https://user-images.githubusercontent.com/19297371/228758824-0c4de91b-24c2-4dd4-a024-52866eb9b1ec.png">

NOTE: Redirects are currently not supported in Windows or MacOs.

**Comment by zhangjiewu** [comment]
did you train with multiple GPUs?

**Comment by Moretai** [comment]
> did you train with multiple GPUs?

说实话 我不知道。今晚回去试试。之前搞的前端，现在对 AI 兴趣盎然
