### ISSUE TITLE
can this repo work on windows cpu machine?

### ISSUE THREAD

**Issue by jackiewangCV** [showlab/Tune-A-Video#47]
I am trying to this repo on my window 10 cpu machine with pre-trained weight
Can this repo work on windows CPU machine?

**Comment by zhangjiewu** [comment]
might work if you just want to generate a few frames (less than 5, i guess), but it will certainly take a very long time to run without gpu. if you do not have a gpu on your local machine, you can use free gpu on colab. [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/showlab/Tune-A-Video/blob/main/notebooks/Tune-A-Video.ipynb)

**Comment by jackiewangCV** [comment]
Hi, Jay
Thanks for your email
