### ISSUE TITLE
请问下下载模型报错，如何解决？

### ISSUE THREAD

**Issue by Fangshaohua8** [showlab/Tune-A-Video#52]
We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like ./checkpoints/stable-diffusion-v1-4 is not the path to a directory containing a scheduler_config.jso
n file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode
上面的地址可以访问，但是会出现上述的报错，请问要如何解决？

**Comment by zhangjiewu** [comment]
可以使用git将模型下载到本地

```
git lfs install
git clone https://huggingface.co/CompVis/stable-diffusion-v1-4
```

**Comment by Fangshaohua8** [comment]
非常感谢。
但是仍然报错：OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory stable-diffusion-v1-4.
似乎还缺少了一些文件

**Comment by zhangjiewu** [comment]
请检查`pytorch_model.bin`是否在clone的文件中，可能是clone的时候出现了错误。

**Comment by Lucca-cherries** [comment]
> 请检查`pytorch_model.bin`是否在clone的文件中，可能是clone的时候出现了错误。

But the stable-diffusion-v1-4 repo (https://huggingface.co/CompVis/stable-diffusion-v1-4/tree/main) does not include these `pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack` files in the main branch. Where can I find them then?
