### ISSUE TITLE
Pose Control Implementation

### ISSUE THREAD

**Issue by Shr1ftyy** [showlab/Tune-A-Video#54]
Hello, 
I was wondering how exactly you guys managed to perform "[pose control](https://tuneavideo.github.io/#:~:text=Pretrained%20T2I%20(pose%20control))" with Tune-A-Video? To my knowledge, the process hasn't been outlined in the Tune-A-Video paper.

![Screen Shot 2023-04-17 at 4 13 21 pm](https://user-images.githubusercontent.com/49330057/232405081-3e0292c0-8e7d-4225-94e9-0b4a037471de.png)

**Comment by zhangjiewu** [comment]
hi @Shr1ftyy, we have some discussions on the pose control part in the sec. 4 of the paper. intuitively, we use [T2I-Adapter](https://github.com/TencentARC/T2I-Adapter) as the pretrained T2I model, and do the editing based on pose condition.

**Comment by Shr1ftyy** [comment]
Thanks for getting back! I realized I was reading an older version of the paper 🤦🏾‍♂️ .

**Comment by Shr1ftyy** [comment]
Hello again, I was wondering if you have any plans to release examples which integrate ControlNet or T2i, etc. with Tune-A-Video for inference. If so, could you provide a timeframe? 

Thanks again for getting back :D

**Comment by zhangjiewu** [comment]
hi @Shr1ftyy, it was actually in my todo list. however, i was quite packed in the past few weeks, and did not manage to do this. feel free to open a PR if you want to contribute. 

fyi, i spotted some following works (e.g., [FollowYourPose](https://github.com/mayuelala/FollowYourPose)) that have implemented the pose control, which is quite similar to ours.

**Comment by Shr1ftyy** [comment]
> hi @Shr1ftyy, we have some discussions on the pose control part in the sec. 4 of the paper. intuitively, we use [T2I-Adapter](https://github.com/TencentARC/T2I-Adapter) as the pretrained T2I model, and do the editing based on pose condition.

Hi, 
In the paper, you claim that:
"
Our method can also be integrated with conditional T2I models like T2I-Adapter [29] and ControlNet [52], to enable di- verse controls on the generated videos at **no extra training cost**.
"
My intuition + the above statement has left me to assume that one does not need to re-finetune a pretrained T2I-Adapter (that's already been trained on Stable Diffusion 1.5 for example) to control a Stable Diffusion 1.5 model that's been modified and fine-tuned as per. the Tune-A-Video paper and the kind of results displayed below (coherent pose-guided imagery):.

![Screen Shot 2023-05-06 at 10 40 14 pm](https://user-images.githubusercontent.com/49330057/236626270-df0ea656-e4a2-4323-b1ef-382210fe5a93.png)


Is this assumption correct?

Thanks again.

**Comment by zhangjiewu** [comment]
yes, there's no need to fine-tune the adapter (control) part. simply focus on fine-tuning the SD1.5 as Tune-A-Video.

**Comment by Tinaa23** [comment]
@zhangjiewu Hi. Amazing work. Is it possible to provide example code on how can we use control mechanism (adapter as is mentioned in the paper) with your model? It is not clear how we can connect the pretrained T2I with pose control to Tune A video.
