### ISSUE TITLE
video prediction

### ISSUE THREAD

**Issue by JWFanggit** [showlab/Tune-A-Video#55]
Hello, your work is very attractive. Can this method be used as a video frame prediction task?

**Comment by zhangjiewu** [comment]
thank you @JWFanggit for the comment. i believe that extending spatial attention to spatiotemporal, which is one of the core ideas of our method, could benefit general temporal modeling. so yes, i think it can be adapted to other video-related tasks, such as video prediction, completion, interpolation, among others. i look forward to seeing the community's progress in this direction.
