### ISSUE TITLE
Question about fine-tuning.

### ISSUE THREAD

**Issue by RuoyuFeng** [showlab/Tune-A-Video#59]
Hi, thanks for your great work!
I'm confused about that if it's required to fine-tune the model for each input model.
What is the purpose of fine-tuning? Is it not enough to simply conduct cross-attention among current frames and previous to keep the consistency?

**Comment by zhangjiewu** [comment]
the purpose of fine-tuning is to improve video consistency. simply applying cross-frame attention can result in poor temporal consistency (e.g., missing frames), as shown in the comparison below.

<table class="center">
<tr>
  <td width=25% style="text-align:center;"><b>Input Video</b></td>
  <td width=25% style="text-align:center;"><b>w/o finetuning</b></td>
  <td width=25% style="text-align:center;"><b>Tune-A-Video</b></td>    
</tr>
<tr>
  <td><img src="https://tuneavideo.github.io/assets/data/car-turn.gif"></td>  
  <td><img src="https://user-images.githubusercontent.com/55792387/234294662-239e0d47-cbed-41f4-8a2f-fcc56c87555a.gif"></td>          
  <td><img src="https://user-images.githubusercontent.com/55792387/234294108-0633609c-6983-4815-8611-85b6c0e33ac1.gif"></td>
</tr>
<tr>
  <td style="text-align:center;" colspan="1">"A jeep car is moving on the road"</td>
  <td style="text-align:center;" colspan="3">"A jeep car is moving on the beach"</td>
</tr>
<tr>
  <td><img src="https://tuneavideo.github.io/assets/data/rabbit-watermelon.gif"></td>         
  <td><img src="https://user-images.githubusercontent.com/55792387/234295400-3a8d2a99-5c9b-4e29-a7cc-018fc4e5012e.gif"></td>   
  <td><img src="https://user-images.githubusercontent.com/55792387/234295910-13d2530e-0db5-45d0-b740-1d937c15ce54.gif"></td>
</tr>
<tr>
  <td style="text-align:center;" colspan="1">"A rabbit is eating a watermelon on the table"</td>
  <td style="text-align:center;" colspan="3">"A cat with sunglasses is eating a watermelon on the beach"</td>
</tr>
</table>

**Comment by RuoyuFeng** [comment]
> the purpose of fine-tuning is to improve video consistency. simply applying cross-frame attention can result in poor temporal consistency (e.g., missing frames), as shown in the comparison below.
> 
> Input Video	w/o finetuning	Tune-A-Video
> ![](https://camo.githubusercontent.com/ea38289b435fc66ee7088e5999ef9d4ecaa23dad8405f80a59adede91e3a094c/68747470733a2f2f74756e6561766964656f2e6769746875622e696f2f6173736574732f646174612f6361722d7475726e2e676966)	![](https://user-images.githubusercontent.com/55792387/234294662-239e0d47-cbed-41f4-8a2f-fcc56c87555a.gif)	![](https://user-images.githubusercontent.com/55792387/234294108-0633609c-6983-4815-8611-85b6c0e33ac1.gif)
> "A jeep car is moving on the road"	"A jeep car is moving on the beach"
> ![](https://camo.githubusercontent.com/ee7cde6027ad3a52a1e4fd146b5d4616be2590b7105cb7fbf983572d52b388ab/68747470733a2f2f74756e6561766964656f2e6769746875622e696f2f6173736574732f646174612f7261626269742d77617465726d656c6f6e2e676966)	![](https://user-images.githubusercontent.com/55792387/234295400-3a8d2a99-5c9b-4e29-a7cc-018fc4e5012e.gif)	![](https://user-images.githubusercontent.com/55792387/234295910-13d2530e-0db5-45d0-b740-1d937c15ce54.gif)
> "A rabbit is eating a watermelon on the table"	"A cat with sunglasses is eating a watermelon on the beach"


Thank you so much for your patient reply and visualization !
Another question is that do we need to fine-tune for each input/reference video? Or we just fine-tune the model on some videos and the model can generate different videos?

**Comment by zhangjiewu** [comment]
in our setting, we fine-tune the pretrained T2I model for each video. however, the approach itself could be applied to other scenarios, for example, few-shot videos as you mentioned. feel free to explore more :)

**Comment by RuoyuFeng** [comment]
> in our setting, we fine-tune the pretrained T2I model for each video. however, the approach itself could be applied to other scenarios, for example, few-shot videos as you mentioned. feel free to explore more :)

Thank you for taking the time to answer my question. Your response was truly insightful and provided me with valuable information. Your work is greatly appreciated!

**Comment by RuoyuFeng** [comment]
Hello again, I have read your paper once again carefully, it's a pretty great work and brought me lots of insights.
I have another question about one detail of your framework design.

In Figure 5 of the paper, why is it necessary to conduct cross-attention on the first frame and the former frame? Why not just use the former two frames (like v_i-1 and v_i-2 instead of v_i-1 and v_1) ? What's the purpose to use the first frame as a condition here, is it used to keep the global consistency so that we can avoid the problem of error propagation? 

Thanks again for your great job and patiently answering my question!

**Comment by zhangjiewu** [comment]
thank you for acknowledging our work! i'm delighted to hear that it has inspired you.

yes, we use the first frame as an anchor for global consistency. using former two frames without the first frame would result in error propagation (visual artifact).

**Comment by RuoyuFeng** [comment]
> thank you for acknowledging our work! i'm delighted to hear that it has inspired you.
> 
> yes, we use the first frame as an anchor for global consistency. using former two frames without the first frame would result in error propagation (visual artifact).

Thank you so much for your detailed and insightful reply. Your expertise has been invaluable and I appreciate your willingness to share your knowledge with me!

**Comment by xiangxin199621** [comment]
![sample-500](https://github.com/showlab/Tune-A-Video/assets/169245314/ebf06c54-ee0f-439a-b8ce-efe858fd3261)
This is the result please tell me how to solve this problem.
My sd version is 1.4.
Thank you!
