### ISSUE TITLE
Support Stable Diffusion 2

### ISSUE THREAD

**Issue by alfredplpl** [showlab/Tune-A-Video#6]
Your work is great! I have generated Anime easily by my model, Cool Japan Diffusion 1.x. 
![test_](https://user-images.githubusercontent.com/3625196/215487593-de25bd0b-5982-4338-8446-3f604f71c53e.gif)
![test](https://user-images.githubusercontent.com/3625196/215487536-f13a1956-ef30-4ebe-b5ad-4710cef25311.gif)

I would like to generate Anime by Stable Diffusion 2.1 because I develop [Cool Japan Diffusion 2.x](https://huggingface.co/spaces/aipicasso/cool-japan-diffusion-latest-demo) that is based on Stable Diffusion 2.1.
Do you plan to support Stable Diffusion 2.1?

**Comment by zhangjiewu** [comment]
There shouldn't be any problem to load the weights from [Stable Diffusion 2.1](https://huggingface.co/stabilityai/stable-diffusion-2-1). Simply modify the `pretrained_model_path` to where the model is saved.

**Comment by alfredplpl** [comment]
OK. Thanks. I could not apply it. However, I have checked that another developer applied it.
