### ISSUE TITLE
Warning from the dancing man‘s fans, true ikun!!!

### ISSUE THREAD

**Issue by JoeZhang01** [showlab/Tune-A-Video#63]
As a true ikun, I can’t stand why do you smear my favorite brother. why don't you try to get to know him? He practice dancing for 25 hours/day  even thought his fever reach 90 degrees Celsius. If the person who is being smeared is you, and what will you do?
🙂Please bring your paper,_Tune-A-Video: One-Shot Tuning of Image Diffusion Models for Text to Video Generation_ , when the court is in session. That's not a joke!!!😡😡😡

**Comment by qaqwqaqwq-0** [comment]
Cold green corpse warning 😡😡😡
