### ISSUE TITLE
Lora weights

### ISSUE THREAD

**Issue by rakesh-reddy95** [showlab/Tune-A-Video#66]
Can I use LoRA weights instead of complete Unet to load and finetune.

**Comment by zhangjiewu** [comment]
yes, you can use lora weights.

**Comment by rakesh-reddy95** [comment]
May i know how I can do that?

**Comment by rakesh-reddy95** [comment]
@zhangjiewu I see that the LoRA weights can be used with the pre-trained SD with UNet2DConditionLoadersMixin but I don't see the support for Unet3D. Tune-A-Video loads the pre-trained SD and adds the temporal attention. What if I have LoRA weights and want to tune-a-video with using those weights, I have to load the attn_procs with Unet3D which is missing.

**Comment by zhangjiewu** [comment]
you can first load the lora weights to the pretrained SD, and then use it for tune-a-video. you can also upgrade the attention file to the latest one in diffusers, which supports lora weights loading with [attention processor](https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/attention_processor.py).

**Comment by rakesh-reddy95** [comment]
Is it the same process with svdiff. As I see svdiff adds 'delta' weights to the same layers where tune -a-video adds 'temp' layers. How can I deal with it?

**Comment by rakesh-reddy95** [comment]
@zhangjiewu I have loaded the lora weights but issue is while doing inference. I see that there will be a mismatch in matrices for cross attention as the lora will be trained on 2D images.

**Comment by rakesh-reddy95** [comment]
Issue is resolved.
