### ISSUE TITLE
Autoregressive

### ISSUE THREAD

**Issue by dlutzzw** [showlab/Tune-A-Video#68]
Hello and thanks for your work. I would like to ask where is the code for autoregressive generation of longer videos, I did not see it in the code. As shown in Figure 11. Autoregressive generation of long video sequence using Sparse-Causal Attention.

**Comment by zhangjiewu** [comment]
thanks for your inquiry. we didn't include this part in the code, since we found it didn't perform very well -- it often leads to videos in the loop. we have removed this part in our [latest arxiv version](https://arxiv.org/pdf/2212.11565.pdf).
